#!/usr/bin/env bun
/**
 * Bundles the bookmarklet runtime into a single minified IIFE and writes it
 * to `apps/web/src/generated/bookmarklet.ts` as a string export that the web
 * app's drag-link component imports.
 *
 * The output is appended with `;void 0;` so that activating the resulting
 * `javascript:` URL never causes the page to navigate to the return value
 * of the expression.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';

const here = new URL('.', import.meta.url).pathname;
const projectRoot = resolve(here, '..', '..');
const entryPoint = resolve(here, 'src/index.ts');
const outPath = resolve(projectRoot, 'apps/web/src/generated/bookmarklet.ts');

const result = await Bun.build({
  entrypoints: [entryPoint],
  format: 'iife',
  target: 'browser',
  minify: true,
  sourcemap: 'none',
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

const [output] = result.outputs;
if (output === undefined) {
  console.error('Build produced no outputs');
  process.exit(1);
}

const raw = (await output.text()).trim();
const payload = raw.endsWith(';') ? `${raw}void 0;` : `${raw};void 0;`;

await mkdir(dirname(outPath), { recursive: true });

const moduleSource = `// AUTOGENERATED by apps/bookmarklet/build.ts — do not edit by hand.
// Regenerate via \`bun --filter '@price-to-impact/bookmarklet' run build\`.

export const bookmarkletSource: string = ${JSON.stringify(payload)};
`;

await writeFile(outPath, moduleSource, 'utf-8');

const kb = (payload.length / 1024).toFixed(1);
const rel = relative(projectRoot, outPath);
console.log(`✓ Bookmarklet bundle: ${payload.length} bytes (${kb} KB) → ${rel}`);
